channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - cxx-compiler
  - fortran-compiler
  - cython
  - openblas
  - conda-build
  - leidenalg
  - matplotlib
  - networkx
  - numba
  - numpy
  - python=3.10
  - scanpy=1.9.7
  - scikit-learn
  - scipy
  - seaborn
  - statsmodels
  - umap-learn
  - cmake
  - lightgbm
  - pip
  - python-annoy
  - ipykernel
  - pigz
  - pip:
    - pandas
    - python-igraph
    - statannotations
    - git+https://github.com/single-cell-genetics/MQuad
    - textalloc
    - zarr==2.14.2 
    - fbpca
    - pysam
    - shap
    - dnaio
    - git+https://github.com/YosefLab/Cassiopeia@master#egg=cassiopeia-lineage
    - plotting_utils
    - circlify
