channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - cxx-compiler
  - fortran-compiler
  - cython
  - conda-build
  - samtools
  - matplotlib
  - numba
  - numpy
  - python=3.9
  - scanpy
  - cmake
  - pip
  - pip:
    - pandas
    - dnaio==0.10.0
    - pysam