channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - cxx-compiler
  - fortran-compiler
  - cython
  - conda-build
  - leidenalg
  - matplotlib
  - networkx
  - numba
  - numpy
  - python=3.9
  - scanpy
  - scikit-learn
  - scipy
  - seaborn
  - statsmodels
  - umap-learn
  - cmake
  - lightgbm
  - pip
  - python-annoy
  - ipykernel
  - pip:
    - pandas
    - pegasusio==0.7.1 
    - pegasuspy==1.7.1
    - python-igraph
    - statannotations
    - mquad
    - textalloc
    - zarr==2.14.2 
    - fbpca
    - hyperopt
    - git+https://github.com/hyperopt/hyperopt-sklearn
